import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#d8dde5",
        "tertiary-container": "#8f9aa8",
        "primary-fixed-dim": "#bcc5d0",
        "secondary-fixed": "#d7dde4",
        "on-primary-fixed-variant": "#5f6976",
        "surface-tint": "#d6dde6",
        background: "#131313",
        "tertiary-fixed": "#edf2f7",
        "secondary-container": "#68717d",
        "inverse-primary": "#96a0ad",
        "on-tertiary-container": "#1b2128",
        "primary-fixed": "#eef3f8",
        "surface-container": "#201f1f",
        "primary-container": "#cfd6df",
        "surface-container-lowest": "#0e0e0e",
        outline: "#9d8ba0",
        "secondary-fixed-dim": "#bfc7d1",
        "surface-container-high": "#2a2a2a",
        "surface-dim": "#131313",
        "surface-container-highest": "#353534",
        secondary: "#bcc5cf",
        "on-secondary-fixed": "#171c22",
        "on-primary-container": "#12161c",
        "outline-variant": "#504254",
        "on-secondary": "#11161b",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "on-tertiary": "#11161b",
        "surface-variant": "#353534",
        "on-surface-variant": "#d4c0d7",
        "on-secondary-fixed-variant": "#5b6470",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#13181e",
        primary: "#d6dde6",
        "error-container": "#93000a",
        "on-primary-fixed": "#161b21",
        "on-tertiary-fixed-variant": "#626b76",
        surface: "#131313",
        "on-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-secondary-container": "#f2f5f8",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#101419",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#bcc4ce",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        neon: "0 0 20px rgba(214, 221, 230, 0.28)",
      },
      letterSpacing: {
        tighter2: "-0.02em",
      },
    },
  },
  plugins: [],
};

export default config;
